version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-node
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: jason
          POSTGRES_DB: test
          POSTGRES_PASSWORD: password
          DATABASE_URL: "postgres://ubuntu@localhost:5432/test"

    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-

      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: bundle exec rspec